name = "bsky-nowplayingat"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "CACHE"
id = "2988ebc3e8eb4be1b87ec5a0aa616dc5"

